  services:
    asknimbus:
      build: .
      container_name: asknimbus_djnagobackend
      restart: always
      command: gunicorn --bind 0.0.0.0:5005 --timeout 240 awschatbackendsettings.wsgi:application
      volumes:  
        - static_volume:/app/static
        - media_volume:/app/media
        - hf_cache:/app/hf_cache
      expose:
        - "5005"
      env_file:
      - .env

    nginx:
      image: nginx:latest
      container_name: nginx_proxy
      restart: always
      ports:
        - "80:80"
      volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - static_volume:/app/static
        - media_volume:/app/media
      depends_on:
        - asknimbus

  volumes:
    static_volume:
    media_volume:
    hf_cache: